info_text = (
    f"🎄 *YANGI YILGA QOLGAN VAQT*\n\n"
    f"📆 Bugungi sana: {today.strftime('%d-%m-%Y')}\n"
    f"🎉 Yangi yil: 01-01-{today.year + 1}\n"
    f"⏳ Qolgan kunlar: *{days_left} kun*\n"
    f"✨ Yangi yilga oz qoldi, tayyorgarlikni boshlang!\n\n"
    f"       ⭐\n"
    f"      🔴🔴\n"
    f"     🔴🎄🔴\n"
    f"    🔵🎄🎄🔵\n"
    f"   🔴🎄🎄🎄🔴\n"
    f"  🔵🎄🎄🎄🎄🔵\n"
    f" 🔴🎄🎄🎄🎄🎄🔴\n"
    f"      🟫🟫\n"
    f"      🟫🟫\n"
    f"   🎁🎁🎁🎁🎁\n"
)

info_text = (
    f"🎄 *YANGI YILGA QOLGAN VAQT*\n\n"
    f"📆 Bugungi sana: {today.strftime('%d-%m-%Y')}\n"
    f"🎉 Yangi yil: 01-01-{today.year + 1}\n"
    f"⏳ Qolgan kunlar: *{days_left} kun*\n"
    f"✨ Yangi yilga oz qoldi, tayyorgarlikni boshlang!\n\n"
    f"```\n"
    f"          ⭐\n"
    f"         🎄\n"
    f"        🎄🎄\n"
    f"       🎄🎄🎄\n"
    f"      🎄🎄🎄🎄\n"
    f"     🎄🎄🎄🎄🎄\n"
    f"    🎄🎄🎄🎄🎄🎄\n"
    f"   🎄🎄🎄🎄🎄🎄🎄\n"
    f"  🎄🎄🎄🎄🎄🎄🎄🎄\n"
    f"         🟫\n"
    f"         🟫\n"
    f"```"
)